import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/sections/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="w-full h-[100vh]" >
        <div className="grid grid-cols-[200px_auto] h-[100vh]">

      <Navbar />
      {children}
        </div>
      </body>
    </html>
    
  );
}
